- src/game/mario_actions_submerged.c
> Fixed moving towards water downslopes

- src/engine/surface_collision.c
- src/game/mario.c
- src/game/mario.h
- src/game/mario_step.c
> frame patch

- include/level_commands.h
- include/special_presets.h
- include/types.h
- src/engine/level_script.c
- src/game/area.c
- src/game/behavior_actions.c
- src/game/macro_special_objects.c
- src/game/object_helpers.h
- src/game/object_list_processor.c
have fun with your 65536 possible models now i guess :/
> 16 bit model IDs

- enhancements/debug_box.patch
- include/config.h
- include/level_commands.h
- include/types.h
- sm64.ld
- src/engine/level_script.c
- src/game/area.c
- src/game/area.h
enjoy your 4 billion possible models i guess :/
> cleaned up my code a bit (also u32 models because eh why not)

- include/config.h
- include/level_commands.h
- include/types.h
- src/engine/level_script.c
also reverted model count to 256 for now
> U16 models (again)

- include/config.h
- src/game/puppycam2.c
- src/game/puppycam2.h
> Puppycam Incline Look Smoothing

- include/config.h
- src/game/area.c
- src/game/debug_box.c
- src/game/debug_box.h
- src/game/game_init.c
- src/game/puppycam2.c
- src/game/puppycam2.h
- src/game/puppyprint.c
- src/game/rendering_graph_node.c
Added some toggable visuals when enabled.
Allows you to see surface collision, as well as object hitboxes.
> Visual Collision Debug

- src/game/game_init.c
- src/game/game_init.h
> Skybox pointer array is now 8 long

- src/game/rendering_graph_node.c
Not a huge change, testing looks good!
> Fixed geo_bone

- asm/n64_assert.s
- sm64.ld
- src/game/crash_screen.c
- src/game/debug.h
Call with `assert((condition you want to be true), "message that fires if condition is false");` anywhere in your code
> Add runtime asserts

- src/game/puppyprint.c
Be holding both L and DPad Up, and press either
> Allow easier command for opening puppyprint debug

- asm/rom_header.s
- src/engine/level_script.c
- src/game/puppycam2.c
- src/game/puppycam2.h
- src/game/puppyprint.c
- src/game/save_file.h
Fixes saving, cannon and flying cameras.
> Puppycamera fixes

- src/game/object_helpers.c
> Fix BUGFIX_DIALOG_TIME_STOP

- asm/rom_header.s
- include/config/config_rom.h
- src/game/save_file.c
- src/game/save_file.h
Not considered important enough to keep
> Remove menudata backup

- src/game/behaviors/unagi.inc.c
> Add COURSE_NUM_TO_INDEX to the save_file_get_star_flags() check in bhv_unagi_init

- src/engine/math_util.c
> Cast return value of approach_s16 to s16

- include/macros.h
- src/game/camera.c
- src/game/mario_actions_moving.c
- src/game/mario_actions_object.c
- src/game/obj_behaviors.c
- src/game/object_helpers.c
- src/game/save_file.c
> Address some more compiler warnings with different define toggles

- src/game/behaviors/cap.inc.c
> Use boolean defines for oCapDoScaleVertically

- src/engine/surface_collision.c
Water used to be face-up only. This allows a ceil-facing check as well.
This also fixes an issue where the water bottom was uncomfortably high. Although, it's strange because: how would somebody fall out of the bottom of water in real life? I feel like it should be the usual buffer of 78 units, so I changed that here as well. 
Here's a video to show that upside down water surfaces are working, and also shows off the water bottom buffer in its new state.
Fixes #176 
https://user-images.githubusercontent.com/79979276/146403158-4575e368-943b-446d-824e-596d1ea60e1b.mp4
> Allow water to face any direction

- src/game/ingame_menu.c
- src/game/rendering_graph_node.c
Fixes #171, tested on Parallel
> Removed superfluous RDP commands when switching microcodes which would override scissor

- data/behavior_data.c
> Set OBJ_FLAG_DONT_CALC_COLL_DIST on bhvUkikiCage

- src/game/game_init.c
> Fixed UNLOCK_FPS strobing

- src/game/behaviors/lll_rotating_hex_flame.inc.c
> Use the vanilla default value for rotating fire bars if bparam2 is 0

- src/game/crash_screen.c
> Fix rumble build

- include/config/config_graphics.h
- src/game/shadow.c
- src/game/shadow.h
> Fix LEGACY_SHADOW_IDS id conflict

- src/engine/math_util.c
> Fixed spline poll code using the wrong values for keyframes

- README.md
- include/config.h
- levels/level_defines.h
- src/engine/extended_bounds.h
- src/engine/surface_load.c
Better credits for individual contributors
> Update readme with better credits

- include/config/config_game.h
- include/config/config_menu.h
> Config documentation

- include/config/config_collision.h
- src/engine/surface_collision.c
- src/engine/surface_collision.h
- src/game/camera.c
> Fix "MAX_REFERENCED_WALLS" typo

- src/audio/external.c
- src/boot/main.c
- src/game/main.h
- src/game/puppyprint.c
> Fixed sAudioEnabled and Puppyprint RDP times

- levels/ttm/areas/3/macro.inc.c
- src/game/behaviors/coin.inc.c
> Fix coin formation coins being deleted if they spawn in the middle of a floor, also fix TTM slide coin position

- src/game/behaviors/chain_chomp.inc.c
> Change chain chomp load/unload distances depending on number of segments

- include/config/config_movement.h
- src/game/mario.c
> Added WATER_PLUNGE_UPWARP define

- README.md
forgot to mention reonucam in the readme credits
> added reonucam credit

- .vscode/c_cpp_properties.json
- include/config/config_audio.h
- include/config/config_debug.h
- include/config/config_game.h
- include/config/config_graphics.h
- include/config/config_movement.h
- include/config/config_objects.h
Please look through config options that I've changed, or suggest new default changes!
> Develop/refactor  default defines

- src/game/mario_step.c
I also reverted the comment cus why not.
> revert air step line to vanilla to fix bitfs scaling platform issue

- src/engine/surface_collision.h
- src/game/mario.c
- src/game/mario_actions_automatic.c
- src/game/mario_actions_cutscene.c
- src/game/mario_actions_submerged.c
- src/game/mario_step.c
Fixes a bug where Mario sometimes checks for ceilings from underneath his plaform when landing.
> Fix stuttering on thin slopes

- include/config/config_debug.h
- src/engine/surface_collision.c
> Swap static and dynamic surface checks back to vanilla order

- src/menu/file_select.c
> Fixed save and quitting while in widescreen

- include/config/config_game.h
> #264: Document non-stop stars' issues

- src/engine/surface_collision.c
I haven't seen frame's wall patch but maybe this way incorrectly translated, or was done wrong initially.
https://user-images.githubusercontent.com/79979276/147650886-579d7acd-a466-47cc-982f-b19c3a09b8f2.mp4
> derive margin_radius from radius after capping at 200

- src/game/mario_actions_airborne.c
> Fix build warning when NO_GETTING_BURIED is enabled

- Makefile
- include/config/config_game.h
> JP Baserom is no longer required for US build

- src/game/behaviors/mr_i.inc.c
> Fix wrong Y offset for Mr. I iris

- include/config/config_rom.h
- src/boot/main.c
"there's no reason why there should be a define that breaks the game when off lmao" -a wise guy
> Make CLEARRAM mandatory

- data/behavior_data.c
> Set oDrawingDistance to 4500 for WF breakable walls

- src/game/level_update.c
> Fix credits text ifdef

- src/game/save_file.c
> Puppycam saves default config on fresh boot

- src/game/ingame_menu.c
> Uncomment the last gSPPopMatrix in render_hud_cannon_reticle

- tools/audiofile/audiofile.cpp
> Fix custom audio files not compiling under MinGW (in case it ever matters)

- include/config/config_objects.h
- src/game/behaviors/water_ring.inc.c
> Reimplement 'FIX_WATER_RINGS'

- src/engine/behavior_script.c
- src/game/rendering_graph_node.c
>  Fix OBJECTS_REJ build error & warning + silhouette incompatibility

- README.md
- src/game/puppycam2.c
- src/game/puppycam2.h
Volumes should build correctly now.
> Puppycamera hotfixes

- include/config/config_movement.h
- src/game/mario_actions_moving.c
Reverts HackerN64/HackerSM64#373
> Revert "Add beta triple jump define"

- src/engine/math_util.c
> Fix construct_float by changing addiu to ori

- include/object_fields.h
- src/game/behaviors/snufit.inc.c
Fixes a gcc11 compiler warning
> Remove redundant snufit offset vector

- include/types.h
- src/game/game_init.c
New `Controller` field whose bits are equal to 1 when the corresponding button is released - basically an inverse of `buttonPressed`.
(ignore the fact that this is coming from my fork of the fangame marathon hack)
> buttonReleased

- include/config/config_audio.h
- src/audio/heap.c
- src/audio/heap.h
- src/audio/synthesis.c
- src/audio/synthesis.h
Originally intended to be just the bugfix, but even that would've required some element of refactoring so I just went all out anyway.
> Bugfix, refactor, and slightly improve BETTER_REVERB runtime

- README.md
- src/game/hud.c
- src/game/hud.h
Adds the following defines for easier HUD modification:
`HUD_BOTTOM_Y`
`HUD_COINS_X`
`HUD_STARS_X`
`HUD_CAMERA_X`
> Add extra hud defines

- .gitattributes
Because otherwise things break and stuff
> Line endings for all text files now forced to \n instead of \r\n

- Makefile
> fix level mesh not updating

- CODEOWNERS
~~Why am I even able to edit this file?~~
> Remove Wiseguy from codeowners file :(

- CODEOWNERS
* Remove Wiseguy from codeowners file :(
* Add ArcticJaguar725 as the primary CODEWOWNER for the moment
> Remove Wiseguy from codeowners file :( (#490)

- include/geo_commands.h
- src/engine/geo_layout.c
- src/engine/geo_layout.h
- src/engine/graph_node.c
- src/engine/graph_node.h
- src/game/rendering_graph_node.c
> Reverted geo bone

- src/game/debug.h
> add error macro that will always fire

- include/level_commands.h
- include/surface_terrains.h
- src/engine/level_script.c
- src/game/area.h
Additionally clean up some inconsistencies surrounding instant warps
> Bugfix: Change instant warps to use ints instead of shorts

- src/boot/main.c
> Bugfix: RCP has gone loud because SOMEONE didn't look at their compiler output

- include/config/config_collision.h
- include/surface_terrains.h
- src/engine/surface_load.c
- src/game/level_update.c
> SURFACE_WARP and death planes use force if set

- include/config/config_collision.h
- include/surface_terrains.h
- src/engine/surface_load.c
- src/game/level_update.c
> Make warp surfaces use the force parameter if set

- include/config/config_debug.h
Because literally who is gonna make a hack without ever using any debug features?
> Disable DISABLE_ALL

- levels/intro/script.c
Idk how the hell I missed this.
> Bugfix: Save & Quit crashes game

- src/game/rendering_graph_node.c
- src/game/rendering_graph_node.h
More things in the repo should do this
> rendering_graph_node layer table updated with gcc extensions for legibility

- include/config/config_rom.h
- src/game/save_file.c
Your custom stuff is only cool when it doesn't get destroyed by somebody else's 120 star save file :(
> Add define for wiping save data if existing save data from vanilla or another hack exists

- levels/ending/geo.c
- src/game/camera.c
> Fix end cake screen crash & flickering

- src/game/screen_transition.c
https://discord.com/channels/879505781916053544/1081604051667538042/1081604051667538042
> Fix transition looping

- src/game/rendering_graph_node.c
haha code not funny work bronke the
> Bugfix: Enabling silhouettes with OBJECTS_REJ disabled does not compile

- Makefile
- tools/.gitignore
- tools/Flips/Flips.cpp
- tools/Flips/crc32.h
- tools/Flips/divsufsort.h
- tools/Flips/divsufsort_private.h
- tools/Flips/errors
- tools/Flips/flips.h
- tools/Flips/global.h
- tools/Flips/libbps.h
- tools/Flips/libips.h
- tools/Flips/libups.h
- tools/Makefile
needs some verification from @someone2639 for both cleanliness and if it works on the funny distro. it just builds flips from scratch!
> added make_patch and flips

- bin/segment2.c
- src/game/ingame_menu.c
- src/game/segment2.h
Fixes #610 and is also a slight performance increase while paused.
> Use FillRectangle for shade_screen

- src/audio/data.c
- src/audio/external.c
- src/audio/heap.c
- src/audio/internal.h
- src/audio/load.c
- src/audio/synthesis.c
- src/audio/synthesis.h
Refactored everything to be more memory efficient and execute fewer function calls than prior
Also accidentally discovered a significant bug with the audio modes always being forced to stereo so this is definitely 2.1 scope lmao
> Improve BETTER_REVERB runtime by about 15-20% overall

- sound/sound_banks/0C_extended_bank.json
Improves the accuracy of the instrument names in bank 0C and adds the missing ones.
> Improved the extended inst names and added missing

- src/engine/surface_load.c
They cause some weird collision bugs, and are thus not worth keeping until properly investigated.
> Revert floor sorting optimizations

- src/game/fasttext.c
Why have we not done this yet?
> Bugfix: fix profiler freeze (hopefully)

- asm/round.s
- sm64.ld
- src/engine/math_util.h
Closes #441 
Rounding works but is about ~2 instructions slower than just having it inline
> Get rid of all inline asm

- src/audio/synthesis.c
- src/audio/synthesis.h
which also improves performance by almost 10% on console
> Slice BETTER_REVERB memory requirements in half

- src/game/ingame_menu.c
Revert dialogue scrolling to behave like vanilla
> Revert C Button Scrolling

- src/game/interaction.c
- src/game/mario_step.c
who told me this would be hard
> Fix the stationary action and ledgegrab downwarps when pushed off a ledge, and added a special downwarp for grabbing Bowser

- Makefile
- tools/Makefile
> Add make rebuildtools

- src/audio/data.c
> Fix typo describing BETTER_REVERB parameters

- src/boot/main.c
- src/game/main.h
Closes #679 once tested more thoroughly
> Track whether the RCP hang timer has started to prevent double setting

- Makefile
> remove dependency on script exec permissions

- bin/segment2.c
- include/config/config_graphics.h
- levels/ccm/areas/2/1/model.inc.c
- src/game/game_init.c
tested on console in spot in BoB that had frust2 issues
> added USE_FRUSTRATIO2 define

- src/game/game_init.c
- src/game/gamecube_controller.c
> Fix controller type checking (GCN false positive)

- src/game/rendering_graph_node.c
Context: Peach cutscene doesn't display correctly at first with world scale set to 1
> remap scale with fov and avoid copy when world scale is 1

- include/config/config_graphics.h
> Remove Puppylights define from config file

- include/config/config_debug.h
- include/config/config_safeguards.h
- src/game/debug.h
Idk how this didn't make it into 2.1. (This also addresses some formatting and throws `UNLOCK_FPS` into the scope of `DISABLE_ALL`.)
> Add DEBUG_ASSERTIONS define and enable it by default

- include/config/config_cutscenes.h
- levels/menu/script.c
This loads Mario A automatically with the smallest amount of changed code possible
Closes #533
> Add file select skip define

- src/audio/effects.c
- src/audio/external.c
- src/audio/internal.h
- src/audio/playback.c
- src/audio/seqplayer.c
- src/audio/synthesis.c
- Remove all version differences from the audio, save for any situations that could be referenced in the future for optimizations
- Also, audio optimizations (mostly lower risk ones because the eventual size of this PR will just turn this into debugging hell)
NOTE: This should be strategically merged and may be best left unsquashed. I will try to keep most of these commits of significant size and amend to older commits if there's any issues that pop up. This will make bisecting for issues more practical in the event bugs surface in the future.
Continued off of #614
> Synthesis Audio Cleanup

- include/config/config_movement.h
- src/game/mario_actions_moving.c
aglab told me yesterday that hackersm64 doesn't have an option to remove buttsliding lag and i thought that was such a disgrace that i needed to fix it.
> Added a define for slope fix

- bin/title_screen_bg.c
- include/config/config_game.h
- levels/intro/geo.c
- src/game/rumble_init.c
- src/menu/intro_geo.c
- src/menu/intro_geo.h
- Missing important reference to `THREAD6_STACK`
- Rumble does not compile
> Fix rumble Issues

- .gitmodules
- .vscode/c_cpp_properties.json
- Makefile
- sm64.ld
- src/game/emutest.c
- src/game/emutest.h
> Add libpl submodule

- src/game/obj_behaviors.c
- src/game/rendering_graph_node.c
Also rewrites some jank in object_step that was allocating a matrix from the gfx pool for zero reason
> Fix objects using throwmatrix having incorrect rotation when paused

- src/engine/math_util.c
- src/engine/surface_collision.c
- src/engine/surface_load.c
- src/engine/surface_load.h
- src/game/debug_box.c
> Save up to 130KB of RAM at literally zero cost

- Makefile
> Change test emulator from mupen64plus to parallel-launcher

- bin/segment2.c
This matches the HUD filtering and just looks better IMO.
> Use G_TF_POINT on 3D billboard numbers

- src/game/puppycam2.c
> Bugfix: Missed purging of debug box flags that no longer exist in Puppycam

- Makefile
- tools/Makefile
- tools/aiff_extract_codebook.c
- tools/sdk-tools/tabledesign/print.c
- tools/sdk-tools/tabledesign/tabledesign.c
- tools/sdk-tools/tabledesign/tabledesign.h
Supposedly this also affects Linux too on rare occasions?
> Fix seg faulting issue with MinGW build system, most likely caused by use of execl
