Makefile
src/audio/heap.c
src/game/game_init.c

Added define 'VC_HACKS' to stub some code that is needed to be booted on Virtual Console. All those patches can be done in binary except for the new option added '-fno-jump-tables'. Unfortunately gcc code generation is creating code that VC recompiler is unable to understand (jump from main function body after JR RA and then back) so I have to add these flag for hacks that might be VC compatible.
In the future 'VC_HACKS' probably should be removed in favor of compiling code that will be compatible with any console but right now it is TBD.

Added temporary VC hacks

---

.vscode/c_cpp_properties.json

This resolves a bunch of stuff that's included everywhere. A lot less useless red squiggles.

added forced includes to c vscode configuration

---

Makefile
asm/debug/map.s
sm64.ld
src/game/crash_screen.c
src/game/map_parser.c
tools/mapPacker.py

- includes a map packer script that can be parsed to get the function name of an arbitrary address
- adds a third page to the crash screen that traverses the stack and spits out names of function pointers it finds

Crash Screen: Report Name of Crashed Function + Stacktrace

---

src/game/object_helpers.c

This is a revert from https://github.com/Reonu/HackerSM64/commit/06494273375b106adc6044e031df605d9ac52909
I restored the original decomp comment as well.

Fixed stale reference bug from obj_mark_for_deletion change

---

src/game/camera.c

Initialize focOffset so that BBH doesn't crash

---

src/game/rendering_graph_node.c

scale was uninitialized, cause broken billboards on emu, and floating point exception on console.
p.s. should scale be applied to _every_ billboarded command? in vanilla scale is only applied if its an object. might be good to consider for v2.1
Fixes #175

fixed geo_process_billboard floating point exception

---

src/game/interaction.c

Fixes #209 
This define only has a gameplay effect with non-exit stars (100 coins, Bowser red coins, etc.).

Re-implement POWER_STARS_HEAL for normal Power Stars

---

src/engine/surface_collision.c
src/engine/surface_collision.h

Fixes #200 
In addition to this, the find_floor functions and their helper functions probably should also be changed to match find_ceil/find_ceil_from_list:
find_floor_from_list:
- unused_find_dynamic_floor
- find_floor
find_water_floor_from_list:
- find_water_floor

Re-implement Y buffer for find_ceil

---

src/game/mario_step.c

Allow stop_and_set_height_to_floor to work at any height if Mario is teleporting

---

src/game/debug_box.c
src/game/rendering_graph_node.c

Fixes #207 
Issue was caused by:
- Bad ifdefs at the end of geo_process_master_list_sub.
- Issues with the debug box dl's.
- The VERTCOUNT define for some reason only being able to use half of the vertex buffer (still needs to be looked into).
Probably needs verification that the issues are fixed on console as well.

Fix VISUAL_DEBUG breaking/crashing when OBJECTS_REJ is disabled

---

src/engine/surface_collision.c
src/engine/surface_collision.h
src/game/rendering_graph_node.c
src/game/shadow.c
src/game/shadow.h

This basically just reorders certain shadow calculations.
List of (related) bugs fixed by this:
- Shadows assuming the custom water surfaces' normals are {0.0,1.0,0.0}
- Shadows not being put on the non-decal transparency layer properly
- Distance to floor not being read properly when a water surface/envbox is present
- correct_lava_shadow_height() not being called for object shadows
- Mario's shadow disappearing when 1024 units above the ground (this was intentional functionality for objects, but made platforming from higher up onto a much lower platform harder, so it's reverted for Mario here. Also, this is the only change here that I think can be split into a separate PR if needed).
- find_water_level_and_floor() was only using the camera or Mario's height for everything, causing …

Fix how shadows handle water/transparency/height

---

data/behavior_data.c
src/game/behaviors/exclamation_box.inc.c
src/game/behaviors/moat_drainer.inc.c
src/game/behaviors/mushroom_1up.inc.c
src/game/behaviors/water_pillar.inc.c
src/game/behaviors/yoshi.inc.c
src/game/level_update.c
src/game/mario_actions_stationary.c
src/game/mario_misc.c
src/game/puppycam2.c

Now it also applies to:
- WMOTR warp (both regular and puppycam)
- Drained moat
- 1-Ups that only appear after Bowser 1 or 2 is beaten
- Yoshi
- Endless stairs
- Castle Toad stars
Fixes #229

Make UNLOCK_ALL apply to more things

---

data/behavior_data.c
include/behavior_data.h
include/config/config_graphics.h
include/object_constants.h
include/object_fields.h
levels/intro/geo.c
levels/intro/leveldata.c
levels/intro/script.c
src/game/behaviors/goomba.inc.c

- `HD_INTRO_TEXTURES` was renamed to `INTRO_CREDIT`
- Created a new define that controls whether to spawn the floombas in the title screen ( `INTRO_FLOOMBAS`). Previously, it was force enabled if both the watermark and the floombas were enabled.
- Enabling `INTRO_FLOOMBAS` automatically enables `FLOOMBAS`
There are no new features here, it just makes the defines regarding the intro less confusing and more flexible.

Renamed HD_INTRO_TEXTURES define, separated intro floombas

---

include/sm64.h

Previously, some of them were calculated using gradians.

Fix hardcoded cos values in sm64.h

---

.vscode/c_cpp_properties.json
Makefile
include/config/config_graphics.h
include/config/config_safeguards.h
src/game/game_init.c
src/game/rendering_graph_node.c

This also fixes microcode point lights on Jabo, since it now recognizes the microcode as MM's.

Fixed hackersm64 using a ucode that never existed

---

src/menu/file_select.c

Combines `render_score_menu_buttons`, `render_copy_menu_buttons`, and `render_erase_menu_buttons` into one function, so that they can be used properly in `load_menu_from_submenu`.
Fixes #298

Combine functions for rendering save file menu buttons

---

src/game/game_init.c
src/game/puppyprint.c

- Invalid hexadecimal syntax for hexadecimal color values will revert the invalid elements back to using the currEnv color. This can be done intentionally if you want certain elements of the currEnv to come back after setting a color such as alpha.
- Example 1: `<COL_-------->` will revert the entire color to match currEnv.
- Example 2: `<COL_FF0000-->` will set the string color to red, while retaining currEnv's alpha color.
- Example 3: `<FADE_FF0000FF,--------,20>` will fade between red and the currEnv color.
- Example 4: `<COL_WWXXYYZZ>` is functionally no different than `<COL_-------->`.
- Lowercase hexadecimal now also supported.
- Various small bugfixes and some updates to comments

Puppyprint color reversion to currEnv + some bugfixes

---

README.md
include/level_commands.h

Sometimes tools like Fast64 will export script.c files with
LOAD_MIO0_TEXTURE() macro "calls" even when you have "YAY0" toggled
under the export menu.  To keep this from being a roadblock for
compilation, LOAD_MIO0_TEXTURE() is defined in this commit as an alias
to the LOAD_YAY0_TEXTURE() macro! :-)

Added LOAD_MIO0_TEXTURE alias for backwards-compatibility

---

src/game/skybox.c

This looks like a pretty bad one

Bugfix: 2x+ skyboxes given insufficient memory space

---

include/config/config_movement.h
src/game/mario_actions_moving.c

IMPORTANT! should be merged immediately
Adds a define to use the beta triple jump, the best thing to put in any hack ever. Uncommented by default of course because everyone wants this in their hack. You are welcome for making the repo so much better.

Add beta triple jump define

---

src/game/skybox.c

The JRB skybox is darkened if you haven't collected JRB's first star. This behaviour should be under `ENABLE_VANILLA_LEVEL_SPECIFIC_CHECKS`

Tie JRB dark skybox with ENABLE_VANILLA_LEVEL_SPECIFIC_CHECKS

---

src/engine/surface_load.c

Saves a lot of CPU over silliness, clearing the final hurdle to just using 4x bounds at all times.

Clear only used dynamic cells

---

src/engine/surface_collision.c

Functionally equivalent find_wall_collisions_from_list, but without any gotos.
Should this be 2.0.1 or 2.1?

Clean up gotos from find_wall_collisions_from_list

---

CODEOWNERS
include/config/config_audio.h
sound/sequences/00_sound_player.s
src/game/behaviors/red_coin.inc.c

Please merge sooner than later, as this is potentially useful as an additional reference to variable red coin counts with 9+ reds.

Add define for using JP red coin sound

---

src/game/level_update.c

This is a partial solution of issue #286.
This decouples the exit course sound from `ENABLE_VANILLA_LEVEL_SPECIFIC_CHECKS`, allowing it to play as long as `DISABLE_EXIT_COURSE` is not defined and `EXIT_COURSE_LEVEL`, `EXIT_COURSE_AREA`, and `EXIT_COURSE_NODE` point to a valid warp. However, the lack of an exit sound for non-lethal warps, such as voiding out of the vanish cap stage, voiding out of TotWC, and similar, isn't fixed by this pull request.
Currently, `init_mario_after_warp` checks against a hard-coded list of `nodeId` values to determine if the sound effect should be played. The vast majority of these are within `LEVEL_CASTLE_GROUNDS`, with one in `LEVEL_CASTLE` checking for a `nodeId` of 32 that I'm unsure of the function of. This will have to be overhauled to fix the other …

Restore exit course sound effect

---

src/game/mario_misc.c

#473
Mario now uses `G_AC_DITHER` if he's either using the vanish cap or teleporting, `G_AC_NONE` otherwise. Previously, the code only checked for vanish cap state, leading to the issue above.

Restore dither effect on teleport

---

src/game/level_update.c
src/game/puppycam2.c

This replaces the remaining `DISABLE_LEVEL_CHECKS` `ifndefs` with correct `ENABLE_VANILLA_LEVEL_SPECIFIC_CHECKS` `ifdefs`. One of the vanilla checks in `src/game/level_update.c` appears to do the same thing as another vanilla check in the same file (namely, make double super extra sure the slide music doesn't get canceled going through a warp in BOB); could we look into whether we could remove one of those?

Clean up remaining DISABLE_LEVEL_CHECKS ifndefs

---

include/config/config_game.h
include/config/config_safeguards.h
src/game/behaviors/mushroom_1up.inc.c
src/game/behaviors/yoshi.inc.c
src/game/hud.c
src/game/ingame_menu.c
src/game/level_update.c
src/game/mario.c
src/game/mario_actions_cutscene.c
src/game/save_file.c
src/game/save_file.h

`ENABLE_LIVES` and `DEFAULT_NUM_LIVES` are now the same define. 
Also, `SAVE_NUM_LIVES` has been removed since it was a super chonky define that, realistically, no one is going to use. 
Fixes #433 
Fixes #438

Simplified lives defines

---

Makefile
tools/Makefile
tools/get_latest_unfloader.py

`make unf` added: build rom then pull the unfloader binary if needed, then load rom in debug mode
also, `make load` will pull unfloader as well!
___
**note: i need a linux tester with an EDX7!**
the way i wrote this should be able to distinguish between linux and wsl, and pull the correct binary. i just dont have a way of easily verifying this atm.
also @someone2639, you know a lot more about makefile shenanigans, lmk if there's anything here that should be changed (or is bad practice). particularly im not sure if i did the `$(LOADER)` target in the most ideal way

Added ability to automatically pull unfloader and build for unf debug

---

Makefile
src/s2d_engine/Makefile
tools/calc_bss.sh

Compiling the project with S2DEX text engine enabled doesn't work on Arch Linux, and neither does the tools/calc_bss.sh script. This commit fixes that.
I'm not really satisfied with how the main Makefile is now structured. I had to move the s2d_engine section down below where CROSS is set for it to work, which isn't great for readability. Suggestions are welcome, as I'm not very experienced with Makefiles.

Fix CROSS variable on multiple environments

---

src/game/area.c

Mario's room sometimes is not reset when warping between different areas, generally when warping from one area with rooms to another without them. This can cause things like doors to not render properly.

Bugfix: Reset Mario's room when switching areas

---

data/behavior_data.c

Whomp's Fortress stationary platforms were given static collision despite being able to delete themselves. This resulted in both a memory leak and stale object referencing that impacted Mario's positioning.

Fix WF Stationary Platforms

---

src/game/skybox.c

Bugfix: skyboxes access tiles out of range when looking straight down

---

data/behavior_data.c
include/object_constants.h
src/engine/behavior_script.c
src/game/object_helpers.c
src/game/object_helpers.h

* Object flag for forcing objects to always be loaded regardless of room
* Does nothing if the object doesn't call bhv_init_room

Make objects not run their code if the room they are in isn't loaded.

---

src/game/behaviors/boulder.inc.c

In vanilla boulders only spawn if mario is in a specific room. This is now wrapped under `ENABLE_VANILLA_LEVEL_SPECIFIC_CHECKS`

Wrap boulder room check under vanilla specific level checks

---

asm/rom_header.s
include/config/config_rom.h
include/n64/PR/os_cont.h
include/n64/PR/os_motor.h
include/sm64.h
include/types.h
sm64.ld
src/game/crash_screen.c
src/game/game_init.c
src/game/game_init.h
src/game/gamecube_controller.c
src/game/mario.c
src/game/rumble_init.c
src/goddard/renderer.c
src/goddard/renderer.h

* Allows Gamecube controllers connected via a passive adapter on console and emulated Gamecube controllers to work as a regular N64 controller would.
* Automatically maps the Gamecube controller C-stick to the C-buttons.
* Adds an option to tell supported emulators (currently just Parallel Launcher) to emulate a Gamecube controller.
* Implements the "Advanced Homebrew ROM Header" format: https://n64brew.dev/wiki/ROM_Header#Advanced_Homebrew_ROM_Header
* Allows developers to check if a Gamecube controller is connected via the `__osControllerTypes` array in `os_cont.h`.
* e.g. `if (__osControllerTypes[0] == CONT_TYPE_GCN) {`
* Allows developers to read Gamecube controller X and Y buttons from `buttonDown` and `buttonPressed` via `GCN_X_BUTTON` and `GCN_Y_BUTTON` macros.
* Allows developers …

Implemented native Gamecube controller support and corresponding emulator hint in ROM header

---

include/surface_terrains.h
src/game/mario.c
src/game/mario_actions_moving.c

Adds a super slippery surface type that forces mario to slide immediately and is good for delimiting the end of a level without resorting to unvisible walls. By aglab.

Add super slippery surface type

---

src/engine/math_util.c
src/engine/math_util.h

`random_u16` returning a `u32` can cause situations where the result is gigantic (even consistently). it should be reverted to be a `u16` again to prevent issues.
example:
`o->oPosX = (f32)((random_u16()/4)-8192);`
printing `o->oPosX` showed `4294964736.000000`

revert random_u16 to be a u16

---

Makefile

These flags have been shown to prevent issues that are caused by `-ffast-math` on console

Added safety gcc math flags

---

Makefile
src/engine/math_util.c
src/engine/math_util.h

- revert `random_u16()` to be a u16
- Added safety gcc math flags
NOTE: Still needs updated version file

HackerSM64 2.0.6

---

include/config/config_graphics.h
src/engine/graph_node.c
src/engine/graph_node.h
src/game/area.c
src/game/rendering_graph_node.c

Updated version of #118, now performance tested and adds GeoProcessJumpTable in rendering_graph_node.c.

Remove GRAPH_NODE_TYPE_FUNCTIONAL + add GeoProcessJumpTable.

---

include/config/config_rom.h
src/audio/synthesis.c
src/boot/main.c
src/game/main.h

This should always be disabled by default.
Fixes #359

Added (emu-only) RCVI hack.

---

src/audio/internal.h

At worst, this eats up a few KB of memory. Runtime difference should be negligible when the extra data is not being used. Primary advantage of this is not cutting off envplayer sequences that are even remotely complex.

Increase max number of concurrent layers and channels

---

sound/sequences/00_sound_player.s
src/audio/effects.c
src/audio/effects.h
src/audio/internal.h
src/audio/playback.c
src/audio/seqplayer.c

Optimize vibrato to even exceed vanilla's implementation, all without restricting usability from the current implementation. This should save up to about 1ms of audio runtime.

Vibrato Optimizations

---

src/buffers/buffers.h
src/game/crash_screen.c
src/game/main.h

Crash screen does not enjoy importing `buffers/buffers.h`.

Bugfix: Stack sizes moved to `game/main.h`

---

include/config/config_audio.h
include/config/config_cutscenes.h
include/level_commands.h
levels/ending/script.c
levels/intro/script.c
levels/menu/script.c
src/audio/data.c
src/audio/data.h
src/audio/external.c
src/audio/external.h
src/audio/heap.c
src/audio/heap.h
src/audio/internal.h
src/audio/load.c
src/audio/port_eu.c
src/audio/port_sh.c
src/audio/synthesis.c
src/audio/synthesis.h
src/audio/synthesis_sh.c
src/engine/level_script.c
src/game/area.c
src/game/area.h
src/game/level_update.c
src/game/sound_init.c
src/hvqm/hvqm.c
src/menu/title_screen.c

- Add preset options for `BETTER_REVERB` to make configuring different reverb parameters between different areas actually practical
- Add `SET_BACKGROUND_MUSIC_WITH_REVERB` and `SET_MENU_MUSIC_WITH_REVERB` level commands to make using different presets in level scripts a breeze (these do not use any additional level script functions or enums)
- Level commands support different presets for console and emulator alike, to allow more intensive processing for emulator without having to throw out console support altogether.
Closes #481

Add support for preset options to be used with BETTER_REVERB

---

src/audio/data.c
src/audio/heap.c
src/audio/internal.h
src/audio/synthesis.c
src/audio/synthesis.h
src/game/puppyprint.c

This can reduce runtime demand down to ~75% of the standard demand, at the cost of the configurability of generally more advanced parameters

Add lightweight configuration settings to BETTER_REVERB

---

src/engine/surface_load.c
src/game/object_list_processor.c
src/game/object_list_processor.h
src/game/spawn_object.c

Clear all references to every object's oFloor each frame when using with dynamic collision. This fixes the issues that presented themselves with the dynamic/static collision introduction. The issue itself was NOT introduced by the collision optimizations, rather it exposed the issue since the surface pool is now shared with the surface node pool, making it possible for entries to be misaligned.
Since object floors were not being cleared each frame while the dynamic collision was, it meant that old object floors would still be pointing to the former addresses of no longer existent collision. This didn't really cause problems beforehand since the stale references would always just end up pointing to a null object, a valid (but possibly incorrect) object, or at worst, a deallocated object. …

Bugfix: Fix Dynamic Collision Shadow Crash

---

src/audio/effects.c
src/audio/effects.h
src/audio/internal.h
src/audio/playback.c
src/audio/synthesis.c

This can help eliminate sample artifacting that happens during a transition between a sudden fade-in into normal volume. It's not completely eliminated due to some processing weirdness, but it's a massive improvement.

Start samples at full velocity when using envelopes that start with a delay of 1

---

src/game/level_update.c
src/game/level_update.h

Fixes the crash that happens when you exit course warp into the same level you're in. The fix is surprisingly simple, it just forces a level reload always when exiting course, which should be how it works anyways when you exit course into the same level.

condition that forces level reload on exit course

---

include/seq_macros.inc
src/audio/effects.c
src/audio/effects.h
tools/assemble_sound.py

This allows sounds to start instantly without any fade-in. Using new soundbanks with delay values of 0 will not compile with base decomp, but old decomp-compliant soundbanks will work with this commit.

Allow envelopes with delay values of 0 on init

---

include/config/config_graphics.h
src/engine/geo_layout.c
src/engine/graph_node.c
src/engine/graph_node.h
src/game/rendering_graph_node.c

GRAPH_RENDER_INVISIBLE is now checked before computing any transformation matrix for the object. Half fov for vertical and horizontal culling is now computed during geo_process_perspective. Vertical culling has been added.
Emulators have basically infinite culling aspect ratio to prevent early culling with widescreen viewport hacks. This was written by both me and Kaze Emanuar, he provided the suggestion to use absolute values to reduce conditions.

Culling improvements + GRAPH_RENDER_INVISIBLE check change

---

Makefile
tools/mapPacker.py

no breaking changes here but now static functions will show up in the crash screen if gcc decides to not completely inline it

convert mapPacker.py to use `nm`

---

data/behavior_data.c
src/engine/behavior_script.c
src/engine/surface_load.c

Dynamic collision will now check Mario´s vertical distance seperately, this is done to implement a check for when mario is above an object, in which case the collision distance is expanded by 2000 units to avoid shadows not appearing.
Or long works correctly now, replaces the behaviour command NOP_1.

Dynamic collision fixes + actual OR_LONG

---

compile_flags.txt

Added `compile_flags.txt` based on `c_cpp_properties.json`. It should allow the clangd lsp to work with more of the codebase by giving it the includes and defines given to vscode.

Create compile_flags.txt for clangd

---

Makefile

Make HackerSM64 actually build
Makefile was relying on a variable it never sets, so it just calls `cat` with no arguments and hangs forever

Fixed broken Makefile

---

extract_assets.py

A long time ago, people used to put all their application data in hidden directories in the home directory. This was very annoying because you would end up with tons of folders in your home directory. And so, the basedir-spec freedesktop specification was made to define where applications should store their user data, and everyone switched to using that. HackerSM64 should do the same.
The specification: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
Simplification from the Arch Linux wiki: https://wiki.archlinux.org/title/XDG_Base_Directory
tl;dr: don't pollute the home directory. Look for the baserom (and any other future things we want to persist across checkouts) in `$XDG_DATA_HOME/HackerSM64` (fallback to `~/.local/share/HackerSM64` if `XDG_DATA_HOME` is …

Look for shared baserom directory using XDG_DATA_DIR instead of polluting the home directory

---

include/config/config_movement.h
include/config/config_safeguards.h
src/game/platform_displacement.c

Still needs cleanup and additional opinions, marking as draft.
• What is the best approach in terms of enums for these? The config files can't actually use enums, so the solution is either to use defines as I am here or put the enum (and define) somewhere else, or change how the movement config is included everywhere.
• Somebody other than me please create a description for what Platform Displacement 2 actually does
• Do we want to add support for separating forwards and backwards momentum? If so, that means even more messy if checks. :(

Add functional changes to inertia to support only specific directions specified in the config

---

Makefile

was accidentally removed by wiseguy for testing. can be up to a 2ms difference in performance so should be set as default. any sort of overrides can be done in another PR

restore mips-n64

---

src/game/object_helpers.c

if you stand on the floor in front of the checker tile towards the DDD painting and look back at the star door, you can see it disappear because you're technically in a different room. Room 0 is _supposed_ to be a non-room, and just preserve the room you're in. This fixes surface objects in rooms in general because that little piece of floor is the DDD painting.

only set rooms while in a new room

---

src/engine/math_util.c

I can provide video evidence if needed. This is needed for raycasts to work at all angles. The difference is really massive, certain geometry in MPAC64 wasn't even clickable unless you had very specific angles or zoom levels, this fixed everything.

Wiseguy's fixed raycast traversal

---

include/config/config_graphics.h
src/game/rendering_graph_node.c

Precison of half fov horizontal being equal to or above 2 leads to many issues. using 1.5 would break rt64 and other emulators with ultra widescreen.
Vertical culling will be disabled by default until 3.0

Important Culling Fixes

---

src/game/behaviors/spawn_star.inc.c

Red coin star marker would otherwise not show up in JRB level replacements

Add missing JRB vanilla level check

---

tools/fixlights.py

Need people to upgrade repos to 2.1 to FULLY test this, though I can confirm it works on geolayouts exported to either actors or levels. 
Specifically what breaks is when a material has F3D lights AND uses tile scrolling. Its a very particular issue. The issue is worse when materials are bled.
I handle this by marking the original DL index and saving the delta offset by changing the command, then i search for texscroll files and update the index of the scrolled commands per material.
Fixes #582

fix tile scrolled light materials

---

asm/emux.s
sm64.ld
src/game/emutest.c

Instead of trying to do a bunch of graphics stuff early on, we can just check for emux support instead since it will be implemented in Ares soon.

Future proof console check (closes #663)

---

Makefile
include/types.h

tested with a c++ file in src/game, and called a function from area.c to confirm it was working and included in the rom. mips-n64 has `mips-n64-g++` though mips-linux-gnu- doesn't seem to come with it by default. since this is just a bonus feature not required by hackersm64 i think its fine to include just in case anybody wants to mess around with things!
i dont think we necessarily need this for 2.1 but its a nice-to-have before i forget about it forever and go to the farm

Cpp support

---

src/game/rendering_graph_node.c

sidenote it wont change anything, but I also initialized `gMatStackIndex` to 0.
Quick summary of the issue:
bekzii reported a fatal crash in PJ64 3.0.1. I confirmed it was easily replicable in PJ64 4.0. After some investigation, we found that the address of a matrix was the float value of 4/3, the aspect ratio.
`gMatStackIndex` was getting decremented too many times. This is due to `geo_process_camera` no longer pushing a camera relative matrix onto the top of the stack, and the old code not getting removed/updated after these changes. Once the "camera" processed the sm64 logo, the mat stack index was getting set to -1, so when accessing that matrix, it was showing the value of the address at `gMatStackIndex`. Now the reason why this only crashes on PJ64 is due to inaccurate RSP behavior, …

removed extraneous mat stack index decrement in geo_process_camera

---

src/audio/synthesis.c

Doing this as a means of documentation actually; I don't care about expected behavior here because almost nobody uses reverb downsampling under normal conditions anyway. The issue is that not having this under a `BETTER_REVERB` ifdef means it'll be easily missed when copying to other repositories, and thus will not function as expected when compared to the previews in HackerSM64.

Preserve vanilla reverb downsampling behavior whenever BETTER_REVERB isn't in use

---

Dockerfile

also:
- Fix outdated package
- Clean up usage example a bit
- Specify a different docker image name/workdir to differentiate this image with that of other forks.
Related pull for sm64ex: https://github.com/sm64pc/sm64ex/pull/538
Related pull for original decomp: https://github.com/n64decomp/sm64/pull/91

Update Dockerfile to Ubuntu 22.04 as 18.04 is EOL

---

data/behavior_data.c
src/engine/surface_collision.c
src/engine/surface_load.c

In vanilla, to account for wall checks while near a cell boundary, each cell actually contains surfaces that lie up to a hardcoded 50 units outside of its boundaries, so that walls aren't missed. This introduces a bug where wall checks greater than 50 units in radius can miss walls (this is noticeable in vanilla when swimming as Mario has a 100 unit radius there, and this bug can be observed in THI). This PR fixes this bug and also improves performance and RAM usage. (This is something Kaze has done in RTYI, and I have also tested it in both rando and Mario Builder.)
* Cells no longer have the 50 unit buffer outside of their boundaries, reducing the number of surface nodes allocated and reducing RAM usage.
* Wall collision checks now use the radius to determine if they should check …

Improved wall collision checking

---

data/behavior_data.c
src/engine/behavior_script.c

Tiny PR that makes the CALL_NATIVE command use 4 bytes instead of 8, saving a few kilobytes of RAM with zero downside.

CALL_NATIVE optimization

---

src/engine/level_script.c

Addresses #570 
Will need a follow-up when #466 is complete to make use of `assertf`

Add relevant model ID asserts to level script load commands

---

include/config/config_graphics.h
src/game/area.c
src/game/level_update.c
src/game/screen_transition.c
src/game/screen_transition.h

Fixed higher time transitions not working (up to 255 frames right now) and fixed transitions not starting properly when interrupting another transition, cleaned up a few things, put every non vanilla styled change into POLISHED_TRANSITIONS and renamed set_and_reset_transition_fade_timer
Arthurtilly and Artic wanted this reverted by default, i think a "correct" full radius counts as a fix and smoothstep fixes the "ended before you'd expect" look that linear has, but I understand now why maybe it should be left commented out by default.
I tried also adjusting the times with POLISHED_TRANSITIONS but it looked very out of place, more than some faster looking transitions did.

Define changes for transitions, two bug fixes

---

src/game/behaviors/boo.inc.c

If a `Go On A Ghost Hunt` Boo is killed while it has a gravity of -1 (at the bottom of its oscillation), and does not hit a wall, it will keep the same negative gravity and continue moving until the textbox is closed. Boo Y speed isn't capped in this scenario, so the constant -1 gravity leads to the boo moving upwards at an increasing rate.
This leads to issues in `boo_act_4`. The distance eventually increases to a point where any other boo object is too far to be returned in `cur_obj_nearest_object_with_behavior`. 
This can have 2 buggy effects:
- the wrong dialog box being brought up if the textbox is delayed (easiest to do by hanging on a ledge).
- the puzzle solved jingle being played incorrectly if you wait in the textbox long enough
This doesn't actually cause issues with King Boo, …

Fix Boo's Accelerating Upwards During Textbox (Vanilla Bug)

---

include/config/config_safeguards.h
include/geo_commands.h
src/engine/geo_layout.c
src/game/crash_screen.c
src/game/debug.h

Fixes #570. Checks if the beginning command of the geo layout is a valid command to start, to make it easier to tell when an invalid model is trying to load.
The check is kinda hardcoded, but doing it with just a range check for a valid geo layout command makes the assert have too many false negatives to be useful.

Add assert for beginning geo layout command

---

bin/segment2.c

This does two things:
1. Restores the `dl_ia_text_tex_settings` from the original Super Mario 64. Not sure why this was changed, consulting the blame says only that "HackerSM64 2.0.0" changed it.
2. Changes the S coordinate of two vertices from `vertex_ia8_char` from 480 to 512. This is an error from the original game, and has been fixed as an enhancement.
The ParaLLEl graphics plugin is not affected. Likewise, no other accurate plugin should be affected by these changes.

Fix weird text on Project64 GLideN64

---

src/game/mario_actions_moving.c

This fixes a bizarre interaction introduced into HackerSM64 some time in 2021. In vanilla SM64, Mario pushes or sidles walls just fine at negative speed. However in Hacker when this happens, Mario freezes in his running animation and turns around, which looks quite bad. This PR should restore the intended vanilla interaction.

Fix wall sidling with negative speed.

---

src/game/behaviors/coin.inc.c
src/game/behaviors/moving_coin.inc.c
src/game/obj_behaviors.h
src/game/obj_behaviors_2.c
src/game/object_helpers.c

* Changed the generic object death function to now also check that an object has landed and is over lava before killing it. Previously it would die instantly if it was above lava which resulted in objects randomly dying above lava
* Also changed the same function to kill a non-buoyant and killable object (e.g. goombas) right when it touches water. Previously it would slowly sink to the bottom and then instantly die upon touching the floor underwater which is strange.
* Changed where lava checks are done so they are done in the same place as other object flag checks. This avoids bugs where e.g. objects die when touching the edge of a platform that is over lava, because the ground flags are updated, then the object's floor is updated to be over the lava, and then the lava move flags are …

Fixed bugs relating to objects dying in lava

---

Makefile

Seemingly provides minor performance benefit and should more importantly reduce perf lotto substantially (hopefully)

Add `-falign-functions=32` to makefile flags

---

Makefile

Checking for directory existence doesn't work because the submodule ends up creating an empty folder.

Fix automatic libpl cloning

---

actors/mario/model.inc.c

Transparency was previously broken because envcolor in the model data was overriding the geo asms that set transparency

Bugfix: Fix Mario's model to use prim instead of envcolor for RGB

---

src/audio/external.c
src/audio/external.h
src/game/behaviors/bbh_merry_go_round.inc.c
src/game/behaviors/piranha_plant.inc.c
src/game/sound_init.c

I've used this function a bunch in my hacks and it's weird that it isn't labelled. It isn't some obscure function you'd never want to use, it's just to cancel the secondary music (like the piranha plant lullaby) and go back to playing the level's music.

Label unlabelled audio func (func_80321080 to stop_secondary_music)

---

data/behavior_data.c
include/config/config_movement.h
include/object_constants.h
src/game/behaviors/bowser.inc.c
src/game/behaviors/tilting_inverted_pyramid.inc.c
src/game/platform_displacement.c
src/game/platform_displacement.h

A few fixes to PD2.
* Makes PD2 default and removes the config define due to the increased stability.
* Fixes bug where jumping off a platform immediately after only being on it for one frame would not apply inertia.
* Fixes bug where ledge-grabbing a laterally moving platform would result in Mario's position being offset.
* Changes OBJ_FLAG_VELOCITY_PLATFORM to OBJ_FLAG_NO_AUTO_DISPLACEMENT
* * This flag now completely overrides the transform displacement rather than just adding to it. This means it can now be used to disable platform displacement entirely on an object as well as being used for TTC treadmills.
* * Gave the flag to the JRB sliding ship box as in vanilla it doesn't displace Mario either.
* Simplified a lot of the PD2 code to take better advantage of the new mathutils

Platform Displacement 2.1

---

src/engine/level_script.c
src/game/area.c
src/game/area.h
src/game/level_update.c

Also add assertions for common warp crashes and remove the hardcoded get_mario_spawn_type table size

Remove destination warp node requirement

---

src/game/behaviors/blue_coin.inc.c

Blue coins can be collected more than once if collected on the final frame of the switch timer when BLUE_COIN_SWITCH_RETRY is enabled. Fixing this on its own isn't enough though, as the blue coin switch also doesn't check for whether that coin was collected when it resets.
Thanks to AleFunky for reporting this!

Bugfix: Blue coin duplication

---

Makefile

this adds compatibility for embedded toolchains, which compile the repo identically, but have a different name.

Add mips64-none-elf- to automatically detected prefixes

---

src/game/behaviors/coin.inc.c

If a spawned coin lands on the same frame it hits the peak of its arc, it will never have vertical speed < 0, so it will never be collectible.
Making this also set the coin to tangible if it has 0 speed fixes this issue.
An example of this bug can be found [here](https://clips.twitch.tv/SpikyBoxyZebraUncleNox-KehYUYBr7DUzRZHG).

Fix spawned coins not being collectible until after their arc's peak

---

src/game/mario_actions_cutscene.c

Self-explanatory; this has been an overdue feature for quite some time imo

Pressing L in debug fly mode heals Mario

---

src/game/level_update.c

Actually do the exit course animation as one would expect when selecting that option (except without clearing the warp checkpoint). This PR also solves the crash when exiting course to the same area (without forcing a level warp).

Improve DEATH_ON_EXIT_COURSE define

---

src/game/mario_actions_airborne.c
src/game/mario_actions_moving.c

Originally from: #706
> Pointing to master for the time being.
> 
> Before this define indiscriminately made you long jump any time you pressed Z at the beginning of ACT_JUMP. there are quite a handful of places where ACT_JUMP is started, so it isnt safe to assume you can always first frame check here. Instead - I just do it while running (ACT_WALKING). Keeps it simple and very likely where people get tripped up over this.
> As an extra layer of safety, this cancels into ACT_CROUCH_SLIDE so that the initial crouch slide checks are taken into consideration.

EASIER_LONG_JUMPS: only long jump with A+Z while running

---

src/engine/surface_load.c

Bug introduced as a result of #786.
I've admittedly not noticed any issues that have resulted from this bug thus far in HackerSM64, but it left move rando in absolute shambles when I ported it over. Either way, it's still a bug and may still have hidden consequences.

Bugfix: Surfaces not able to be placed at the beginning of a partition

---

tools/assemble_sound.py

- Fix Zone.Identifier files counting as a soundbank index
- Throw error if m64 index gap is detected (e.g. when going from `29_mysequence.m64` to `30_mysequence.m64` instead of `2A_mysequence.m64`
Both of these issues are capable of causing game crashes at best, and stealthy yet severe game corruption at worst.

Bugfix: assemble_sound.py build corruption issues

---

fast64.json

Allows fast64 to know a repo's ideal settings as soon as decomp path is picked. Settings are the default except for:
- Matstack Fix is on
- Microcode is set to EX2
- Force Extended RAM is off because hackersm64 already has it enabled by default
- Refresh is set to HackerSM64 2.3.0 (Refresh 13)

Add Fast64 repo settings file (fast64.json)
